# Generated by Django 4.1.6 on 2023-04-18 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edusphere', '0005_alter_masterinstitutes_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='educationInstitute',
            field=models.CharField(blank=True, default='Harvard University', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateModified', models.DateTimeField(auto_now=True, null=True)),
                ('threadId', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('senderId', models.CharField(blank=True, choices=[('user1', 'u1'), ('user2', 'u2')], max_length=5, null=True)),
                ('isInActive', models.BooleanField(default=False)),
                ('isInActiveDate', models.DateTimeField(blank=True, null=True)),
                ('tempChar', models.CharField(blank=True, max_length=100, null=True)),
                ('tempInt', models.IntegerField(blank=True, null=True)),
                ('tempJson', models.JSONField(blank=True, null=True)),
                ('userId1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_1', to=settings.AUTH_USER_MODEL)),
                ('userId2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
