# Generated by Django 4.1.6 on 2023-04-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusphere', '0007_chatmodel_messagedatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='messageSenderId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='educationInstitute',
            field=models.CharField(blank=True, default='Harvard University', max_length=200, null=True),
        ),
    ]
